### ISSUE TITLE
decreasing and increasing are based on what ?

### ISSUE THREAD

**Issue by Memoi** [yasinkuyu/binance-trader#111]
Hi,

I don't understand what I need to set in decreasing and increasing.
I tried this "0.000001" because in binance for OMG/ETH this is the min price, the script buy once then show error Filter failure: PRICE_FILTER.

I use the devx version, thanks for your help

https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule
11 | OMG/ETH | 0.01 | OMG | 0.000001 | ETH | 0.02 | ETH

**Comment by shawnryan131** [comment]
Yes, you have to use the minimum for each of those values. That increasing/decreasing value needs to be the same or the bot will do the opposite thing. What I believe it does is it slowly increases/decreases the amount the bot tries to buy the item by (in ETH or whatever) and the smaller you put it, the smaller the value. So... it'll try to buy at 0.0021 Eth and if you can't then it'll try to buy at 0.0020 over time. but the SELL does NOT decrease like the buy one does. Something is messed up. The sale price does NOT try to sell at a lower price, which needs fixing because I have sale orders the bot made that are never made and nothing ever happens. 

Try putting a negative number in front of them, I think it corrects the issues with buying high and selling low. (-.000001).

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/75863359d84c5c4c9fa552202eb09331217004fe
