### ISSUE TITLE
Illigal character in price

### ISSUE THREAD

**Issue by LoneWolfProductions** [yasinkuyu/binance-trader#29]
the lower i put the profit the faster i get the error. maybe this can help identify the error?

**Comment by Foof811** [comment]
it seems to be random. Just like unknown error and insufficient balance error.

**Comment by saumitrabhave** [comment]
If you are talking about following error
`Error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.`

For me it was floating number format issue. The prices were formatted in scientific notation . For me the fix was to replace the API python code as following

`def buy_limit(self, market, quantity, rate):
        path = "%s/order" % self.BASE_URL
        params = {"symbol": market, "side": "BUY", \
            "type": "LIMIT", "timeInForce": "GTC", \
            "quantity": quantity, "price": '%.8f' % rate}
        return self._post(path, params)`
