### ISSUE TITLE
Sample Code for market order

### ISSUE THREAD

**Issue by HammadAWS** [yasinkuyu/binance-trader#30]
I have made a change in the code and have placed market Buy order instead of limit order.
But after getting Order ID, I am not able to get price at which the coin is bought. Can anyone help me in giving me the sample code?
Thanks!!

**Comment by Foof811** [comment]
yeah it seems to be the main issue with the code, is that it tries to buy it at the limit amount, and then immediately tries to sell it without checking if it actually has it or not, which leaves an open order and causes the script to crash because it didn't actually buy the order, it just created it, and thinks it's in the balance.

**Comment by Foof811** [comment]
@HammadAWS has it worked successfully by changing it to market prices?

**Comment by HammadAWS** [comment]
Buy is successful, it returns the order ID, but i am not able to find the price at which the item was bought.
If i don't know the price, how will I sell it...

**Comment by Foof811** [comment]
are you trying to sell it manually or with the script?

**Comment by Foof811** [comment]
Because with the script, if it fulfills the buy order, most of the time it will give an unknown order error and cancel anyway instead of selling
