### ISSUE TITLE
Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by Memoi** [yasinkuyu/binance-trader#96]
Hello,

I have this error when i tried to buy ETH or NEO but it's working for VIBE, VEN, BCD...

m: Filter failure: PRICE_FILTER

![filter failure](https://user-images.githubusercontent.com/35448059/34946213-40ac162c-fa06-11e7-863f-ff210d3279f9.PNG)

Example
python trader.py --symbol NEOBTC --quantity 1 --profit 0.8
python trader.py --symbol ETHBTC --quantity 0.1 --profit 0.5

**Comment by riveryc** [comment]
This is due to https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule
The minimum price for NEOBTC: 0.000001, however, you are trying to buy & sell with 0.00000100, so the API won't accept it.
Application should validate & re-format the price calculated with exchangeInfo -> symbol -> filters -> minPrice or tickSize

I'm quite new to this project only today, so cannot say more. Will try to make some changes and see how it goes bit later.

**Comment by riveryc** [comment]
What you also can do is using "--increasing 0.0000001 --decreasing 0.0000001" to define the increase and decrease value to replace the default one with 0.00000001 which causing format issue. But I still think it will be more convenience to have application itself to detect it.

**Comment by Memoi** [comment]
Thanks ☺️

**Comment by yasinkuyu** [comment]
@riveryc Thanks https://github.com/yasinkuyu/binance-trader/commit/75863359d84c5c4c9fa552202eb09331217004fe

**Comment by rparsel** [comment]
any ideas why im getting this message when the app trys to sell, it can buy fine

2021-02-15 20:17:56,164,164 INFO CTSIBNB: Buy order filled... Try sell...
Message : Filter failure: PRICE_FILTER
